# Generated by Django 5.0 on 2023-12-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "addressid",
                    models.IntegerField(
                        db_column="AddressID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "addressline1",
                    models.CharField(db_column="AddressLine1", max_length=60),
                ),
                (
                    "addressline2",
                    models.CharField(
                        blank=True, db_column="AddressLine2", max_length=60, null=True
                    ),
                ),
                ("city", models.CharField(db_column="City", max_length=30)),
                (
                    "stateprovince",
                    models.CharField(db_column="StateProvince", max_length=50),
                ),
                (
                    "countryregion",
                    models.CharField(db_column="CountryRegion", max_length=50),
                ),
                ("postalcode", models.CharField(db_column="PostalCode", max_length=15)),
                ("rowguid", models.CharField(max_length=36)),
                ("modifieddate", models.DateTimeField(db_column="ModifiedDate")),
            ],
            options={
                "db_table": "Address",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_column="id", primary_key=True, serialize=False
                    ),
                ),
                ("namestyle", models.BooleanField(db_column="NameStyle")),
                (
                    "title",
                    models.CharField(
                        blank=True, db_column="Title", max_length=8, null=True
                    ),
                ),
                ("firstname", models.CharField(db_column="FirstName", max_length=50)),
                (
                    "middlename",
                    models.CharField(
                        blank=True, db_column="MiddleName", max_length=50, null=True
                    ),
                ),
                ("lastname", models.CharField(db_column="LastName", max_length=50)),
                (
                    "suffix",
                    models.CharField(
                        blank=True, db_column="Suffix", max_length=10, null=True
                    ),
                ),
                (
                    "companyname",
                    models.CharField(
                        blank=True, db_column="CompanyName", max_length=128, null=True
                    ),
                ),
                (
                    "salesperson",
                    models.CharField(
                        blank=True, db_column="SalesPerson", max_length=256, null=True
                    ),
                ),
                (
                    "emailaddress",
                    models.CharField(
                        blank=True, db_column="EmailAddress", max_length=50, null=True
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, db_column="Phone", max_length=25, null=True
                    ),
                ),
                (
                    "passwordhash",
                    models.CharField(db_column="PasswordHash", max_length=128),
                ),
                (
                    "passwordsalt",
                    models.CharField(db_column="PasswordSalt", max_length=10),
                ),
                ("rowguid", models.CharField(max_length=36)),
                (
                    "modifieddate",
                    models.DateTimeField(db_column="ModifiedDate", null=True),
                ),
            ],
            options={
                "db_table": "Customer",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Customeraddress",
            fields=[
                (
                    "addressid",
                    models.IntegerField(
                        db_column="AddressID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "addresstype",
                    models.CharField(db_column="AddressType", max_length=50),
                ),
                ("rowguid", models.CharField(max_length=36)),
                ("modifieddate", models.DateTimeField(db_column="ModifiedDate")),
            ],
            options={
                "db_table": "CustomerAddress",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "productid",
                    models.IntegerField(
                        db_column="ProductID", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="Name", max_length=50)),
                (
                    "productnumber",
                    models.CharField(db_column="ProductNumber", max_length=25),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, db_column="Color", max_length=15, null=True
                    ),
                ),
                (
                    "standardcost",
                    models.DecimalField(
                        db_column="StandardCost", decimal_places=4, max_digits=19
                    ),
                ),
                (
                    "listprice",
                    models.DecimalField(
                        db_column="ListPrice", decimal_places=4, max_digits=19
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True, db_column="Size", max_length=5, null=True
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        db_column="Weight",
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "productcategoryid",
                    models.IntegerField(
                        blank=True, db_column="ProductCategoryID", null=True
                    ),
                ),
                (
                    "productmodelid",
                    models.IntegerField(
                        blank=True, db_column="ProductModelID", null=True
                    ),
                ),
                ("sellstartdate", models.DateTimeField(db_column="SellStartDate")),
                (
                    "sellenddate",
                    models.DateTimeField(
                        blank=True, db_column="SellEndDate", null=True
                    ),
                ),
                (
                    "discontinueddate",
                    models.DateTimeField(
                        blank=True, db_column="DiscontinuedDate", null=True
                    ),
                ),
                (
                    "thumbnailphoto",
                    models.BinaryField(
                        blank=True, db_column="ThumbNailPhoto", null=True
                    ),
                ),
                (
                    "thumbnailphotofilename",
                    models.CharField(
                        blank=True,
                        db_column="ThumbnailPhotoFileName",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("rowguid", models.CharField(max_length=36)),
                ("modifieddate", models.DateTimeField(db_column="ModifiedDate")),
            ],
            options={
                "db_table": "Product",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Productcategory",
            fields=[
                (
                    "productcategoryid",
                    models.IntegerField(
                        db_column="ProductCategoryID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "parentproductcategoryid",
                    models.IntegerField(
                        blank=True, db_column="ParentProductCategoryID", null=True
                    ),
                ),
                ("name", models.CharField(db_column="Name", max_length=50)),
                ("rowguid", models.CharField(max_length=36)),
                ("modifieddate", models.DateTimeField(db_column="ModifiedDate")),
            ],
            options={
                "db_table": "ProductCategory",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Productdescription",
            fields=[
                (
                    "productdescriptionid",
                    models.IntegerField(
                        db_column="ProductDescriptionID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "description",
                    models.CharField(db_column="Description", max_length=400),
                ),
                ("rowguid", models.CharField(max_length=36)),
                ("modifieddate", models.DateTimeField(db_column="ModifiedDate")),
            ],
            options={
                "db_table": "ProductDescription",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Productmodel",
            fields=[
                (
                    "productmodelid",
                    models.IntegerField(
                        db_column="ProductModelID", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="Name", max_length=50)),
                (
                    "catalogdescription",
                    models.TextField(
                        blank=True, db_column="CatalogDescription", null=True
                    ),
                ),
                ("rowguid", models.CharField(max_length=36)),
                ("modifieddate", models.DateTimeField(db_column="ModifiedDate")),
            ],
            options={
                "db_table": "ProductModel",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Salesorderdetail",
            fields=[
                (
                    "salesorderdetailid",
                    models.IntegerField(
                        db_column="SalesOrderDetailID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("orderqty", models.SmallIntegerField(db_column="OrderQty")),
                (
                    "unitprice",
                    models.DecimalField(
                        db_column="UnitPrice", decimal_places=4, max_digits=19
                    ),
                ),
                (
                    "unitpricediscount",
                    models.DecimalField(
                        db_column="UnitPriceDiscount", decimal_places=4, max_digits=19
                    ),
                ),
                (
                    "linetotal",
                    models.DecimalField(
                        db_column="LineTotal", decimal_places=6, max_digits=38
                    ),
                ),
                ("rowguid", models.CharField(max_length=36)),
                ("modifieddate", models.DateTimeField(db_column="ModifiedDate")),
            ],
            options={
                "db_table": "SalesOrderDetail",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Salesorderheader",
            fields=[
                (
                    "salesorderid",
                    models.IntegerField(
                        db_column="SalesOrderID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "revisionnumber",
                    models.SmallIntegerField(db_column="RevisionNumber"),
                ),
                ("orderdate", models.DateTimeField(db_column="OrderDate")),
                ("duedate", models.DateTimeField(db_column="DueDate")),
                (
                    "shipdate",
                    models.DateTimeField(blank=True, db_column="ShipDate", null=True),
                ),
                ("status", models.SmallIntegerField(db_column="Status")),
                ("onlineorderflag", models.BooleanField(db_column="OnlineOrderFlag")),
                (
                    "salesordernumber",
                    models.CharField(db_column="SalesOrderNumber", max_length=25),
                ),
                (
                    "purchaseordernumber",
                    models.CharField(
                        blank=True,
                        db_column="PurchaseOrderNumber",
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "accountnumber",
                    models.CharField(
                        blank=True, db_column="AccountNumber", max_length=15, null=True
                    ),
                ),
                (
                    "shiptoaddressid",
                    models.IntegerField(
                        blank=True, db_column="ShipToAddressID", null=True
                    ),
                ),
                (
                    "billtoaddressid",
                    models.IntegerField(
                        blank=True, db_column="BillToAddressID", null=True
                    ),
                ),
                ("shipmethod", models.CharField(db_column="ShipMethod", max_length=50)),
                (
                    "creditcardapprovalcode",
                    models.CharField(
                        blank=True,
                        db_column="CreditCardApprovalCode",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        db_column="SubTotal", decimal_places=4, max_digits=19
                    ),
                ),
                (
                    "taxamt",
                    models.DecimalField(
                        db_column="TaxAmt", decimal_places=4, max_digits=19
                    ),
                ),
                (
                    "freight",
                    models.DecimalField(
                        db_column="Freight", decimal_places=4, max_digits=19
                    ),
                ),
                (
                    "totaldue",
                    models.DecimalField(
                        db_column="TotalDue", decimal_places=4, max_digits=19
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, db_column="Comment", null=True),
                ),
                ("rowguid", models.CharField(max_length=36)),
                ("modifieddate", models.DateTimeField(db_column="ModifiedDate")),
            ],
            options={
                "db_table": "SalesOrderHeader",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DevelopmentModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
