# Generated by Django 4.1 on 2023-05-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=100)),
                ('user_phone', models.CharField(max_length=100)),
                ('user_address', models.CharField(max_length=100)),
                ('user_city', models.CharField(max_length=100)),
            ],
        ),
    ]
