version: '3.8'
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  backend:
    image: mcr.microsoft.com/vscode/devcontainers/base:ubuntu-22.04
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspaces/Homepage:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
 
