version: '3.8'
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:ubuntu-22.04
    container_name: devcontainer
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ../:/workspaces/:cached
    command: sleep infinity
  
  
  # Configuration to split the backend and frontend into separate containers
  # backend:
  #   build:
  #     context: ../backend
  #     dockerfile: Dockerfile
  #   container_name: api_backend
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     # Update this to wherever you want VS Code to mount the folder of your project
  #     - ../:/workspaces/:cached
  #   # Overrides default command so things don't shut down after the process ends.
  #   command: sleep infinity

  # frontend:
  #   build:
  #     context: ../frontend
  #     dockerfile: Dockerfile
  #   container_name: client_frontend
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ../frontend:/workspaces/frontend:cached
  #   command: sleep infinity
  #   depends_on:
  #     - backend

  
    
 
